config/routes.rb
Rails.application.routes.draw do
	# Admin routes
	namespace :admin do
		resources :task_lists, :tasks, :categories

		put '/tasks/:id/move/:dir', to: 'tasks#move', as: 'move_task'
		patch'/tasks/:id/move/:dir', to: 'tasks#move'

	end

	# User routes
	resources :task_lists, :tasks, :categories
	
	put '/tasks/:id/move/:dir', to: 'tasks#move', as: 'move_task'
	patch'/tasks/:id/move/:dir', to: 'tasks#move'

	get '/user/new', to: 'users#new', as: 'new_user'
	post '/user', to: 'users#create', as: 'users'

	get '/user/sign_in', to: 'sessions#new', as: 'new_session'
	post '/user/session', to: 'sessions#create', as: 'sessions'
	delete '/user/sign_out', to: 'sessions#destroy', as: 'session'


	#root 'task_lists#index'
	root to: 'welcome#index'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task_list.rb
class TaskList < ApplicationRecord
	##
	# TaskList properties (property_name: type => db_column_name: type?)
	#	* id: integer => id: primary key
	#	* name: string => name
	#	* user: User => user_id: foreign key
	#	* created_at: timestamp => created_at
	#	* updated_at: timestamp => updated_at
	#	* tasks: Tasks[] => N/A: virtual property

	# Associations
	has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
	belongs_to :user
	# belongs_to :categories_task_list
	# TODO: Is through needed?
	has_and_belongs_to_many :categories#, :through => :categories_task_list
	# belongs_to :user

	# Validations
	validates :name, presence: { message: "Task list name cannot be empty"}, length: { maximum: 100, too_long: "The name must be fewer than 100 characters."}
	validates :user_id, presence: true
end

app/controllers/admin/task_lists_controller.rb
module Admin
	class TaskListsController < ::TaskListsController
		def index
			sort = (params[:sort] || "name") + " " + (params[:dir] || "asc")

			query = "#{(params[:query] || "").downcase}%"
			conds = ["LOWER(name) LIKE ?", query]

			@task_lists = TaskList.paginate(page: params[:page] || 1, per_page: 10).where(conds).order(sort)
		end
	end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index # TODO: SELECT * FROM task_lists WHERE user_id = <authenticated_user_id>
    @task_lists = TaskList.where(user_id: session[:user_id]).order(:name)
    if !self.logged_in?
      respond_to do |format|
        flash[:error] = "You must be logged in to go to that page"
        format.html { redirect_to new_session_url }
        format.json { render "sessions/new", status: :unauthorized, location: :session}
      end
    end
    #@task_lists = TaskList.all.order(:name)
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
    # @task_list = TaskList.find(params[:id])
    @tasks = TaskList.find(params[:id]).tasks
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)
    @task_list[:user_id] = current_user().id
    logger.debug 'task_lists#create called'
    logger.debug @task_list.inspect
    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html do 
          flash[:error] = @task_list.errors.messages.values
          render :new, error: @task_list.errors

        end
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params.require(:task_list).permit(:name)
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
 <%= semantic_form_for @task_list do |f| %>
    <%= f.inputs :name, :user_id %>
    <%= f.actions :submit, :cancel %>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<div class="col-6 list-main container">
  <div class="row list-head">
    <h1>My Tasks</h1>
    <%#= link_to 'New Task List', new_task_list_path %>
    <a data-toggle="modal" data-target="#newTaskListModal">
      New Task List
    </a>
  </div>
  <div class="row list-body">
    <ul class="list-group">
      <% @task_lists.each do |list| %>
        <li class="list-group-item">
          <%= link_to list.name, list %>
          <%# edit_task_list_path(list) %>
          <span class="badge task-count"><%= list.tasks.count %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="modal fade" id="newTaskListModal" tabindex="-1" role="dialog" aria-labelledby="newTaskList">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="newTaskList">New Task List</h3>
      </div>
      <%= form_for TaskList.new do |form| %>
      <div class="modal-body">
        
          <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control', placeholder: 'List Name', autofocus:true %>
          </div>
          <%#= form.input :user, as: :select, collection: User.all, label: false %>
          <!--div class="form-group">
          <%#= form.label :user_id %>
          <%#= form.select :user_id, options_from_collection_for_select(User.all, "id", "login"), { include_blank: true }, { class: 'form-control' } %>
          </div-->
          <%#=  %>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
      </div>
       <% end %>
    </div>
  </div>
</div>
<!--br-->

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%#= render 'form', task_list: @task_list %>
<%= render 'form'%>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<div class="row">
  <div class="list-main container">
    <!-- List Head -->
    <div class="row list-head">
      <div class="navbar navbar-default" role="navigation">
        <!-- Navbar Head -->
        <div class="navbar-header">
          <a class="navbar-brand"><%= @task_list.name %></a>
        </div>
        <!-- Navbar Body -->
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!-- Edit Dropdown -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Edit <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a data-href="">
                    <span class="glyphicon glyphicon-pencil"></span> Rename
                  </a>
                </li>
                <li>
                  <a data-href="">
                    <span class="glyphicon glyphicon-plus"></span> Add Category
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a data-href="">
                    <span class="glyphicon glyphicon-trash"></span> Delete List
                  </a>
                </li>
              </ul>
            </li>
            <!-- /Edit Dropdown-->
            <li>
              <a href="" type="button" data-toggle="modal" data-target="#new-task-modal">New Task</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- List Body -->
    <div class="row list-body">
      <ul class="list-group">
        <% @tasks.each do |task| %>
          <li id="task-<%= task.id %>" class="list-group-item">
            <div class="task-display-view" id="<%= task.id %>">
              <form class="task-completed" action="<%= task_url(task) %>", method="post", data-remote="true" style="display: inline;">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                <%= check_box_tag 'task[status]', :completed, task.status == "completed", class: "status-checkbox"%>
              </form>
              <span class="task-name"><%= task.name %></span>
              <span class="dropdown manage-task">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <span class="glyphicon glyphicon-menu-hamburger"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li>
                    <a class="move-up" data-href= "<%= move_task_url(task, :up) %>" data-count="1"><span class="glyphicon glyphicon-triangle-top"></span> Move Up</a>
                  </li>
                  <li>
                    <a class="move-down" data-href="<%= move_task_url(task, :down) %>" data-count="1"><span class="glyphicon glyphicon-triangle-bottom"></span> Move Down</a>
                  </li>
                  <li>
                    <a class="edit-task" data-id="<%= task.id %>"><span class="glyphicon glyphicon-cog"></span> Edit</a>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to "#", :href => task_url(task, :list => params[:id]), :class => "task-delete-link", :method => :delete, :remote => true, "data-confirm".to_sym => "Are you sure you want to delete this task?" do%>
                      <span class="glyphicon glyphicon-trash"></span> Delete
                    <% end %>
                  </li>
                </ul>
              </span>
            </div>
            <div class="task-display-edit" id="<%= task.id %>">
              <form action="/tasks/<%= task.id %>" method="post" data-remote="true">
                <input name="_method" type="hidden" value="put" />
                <div class="input-group">
                  <input type="text" class="form-control" value="<%= task.name %>" autofocus name="task[name]">
                  <span class="input-group-btn">
                    <button class="btn btn-success submit-edit" type="submit" role="submit-changes">
                      <span class="glyphicon glyphicon-ok"></span>
                    </button>
                    <button class="btn btn-danger cancel-edit" type="button" role="cancel-changes" data-id="<%= task.id %>" data-og-name="#{name}">
                      <span class="glyphicon glyphicon-remove"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!-- New Task Modal -->
<div class="modal fade" id="new-task-modal" tabindex="-1" role="dialog" aria-labelledby="new-task-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="new-task-modal">New Task</h3>
      </div>
      <div class="modal-body">
        <%= form_for Task.new do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Task Name" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
          </div>
          <%#=  %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" role="cancel">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
        <button type="button" class="btn btn-success create create-form" role="create">
          <span class="glyphicon glyphicon-ok"></span>
        </button>
      </div>
    </div>
  </div>
</div>