config/routes.rb
Rails.application.routes.draw do
	# Admin routes
	namespace :admin do
		resources :task_lists, :tasks, :categories

		put '/tasks/:id/move/:dir', to: 'tasks#move', as: 'move_task'
		patch'/tasks/:id/move/:dir', to: 'tasks#move'

	end

	# User routes
	resources :task_lists, :tasks, :categories
	
	put '/tasks/:id/move/:dir', to: 'tasks#move', as: 'move_task'
	patch'/tasks/:id/move/:dir', to: 'tasks#move'

	get '/user/new', to: 'users#new', as: 'new_user'
	post '/user', to: 'users#create', as: 'users'

	get '/user/sign_in', to: 'sessions#new', as: 'new_session'
	post '/user/session', to: 'sessions#create', as: 'sessions'
	delete '/user/sign_out', to: 'sessions#destroy', as: 'session'


	#root 'task_lists#index'
	root to: 'welcome#index'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!--div class="navbar nav-default nav-fixed-bottom"-->
<footer class="container-fluid">
	<div class="row">
		<a href="https://github.com/DonIsaac" target="blank">
			<span class="social-icon">
				<%= image_tag image_path 'github_logo.svg' %>
			</span>
		</a>
	</div>
	<div class="row justify-content-center">
		<h5>Copyright &copy; 2019 Donald Isaac. All Rights Reserved.</h5>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header style="padding-bottom: 70px;">
  	<nav class="navbar navbar-default navbar-fixed-top">
    	<div class="container-fluid">
			<div class="navbar-header">
				<a href="/">
					<span class="navbar-brand">Taskr</span>
				</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
						<li>
							<!--a href="#">My Tasks</a-->
							<%= link_to 'My Tasks', task_lists_path %>
						</li>
						<li class="dropdown">
							<a href="#" data-toggle="dropdown">
								<%= current_user().firstname %> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a id="my-profile" href="#<%#=  %>">
									<span class="glyphicon glyphicon-user"></span> My Profile
									</a></li> 
								<li><a id="sign-out" data-href="<%= session_url %>">
									<span class="glyphicon glyphicon-off"></span> Sign Out
									</a></li>
							</ul>
						</li>
					<% else %>
						<li>
							<%= link_to 'Sign Up', new_user_path %>
        				</li>
        				<li>
							<%= link_to 'Sign In', new_session_path %>
						</li>
					<% end %>
        			
			</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
		</button>
		<%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:error] %>
	<% flash[:error].each do |err| %>
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span class="glyphicon glyphicon-remove"aria-hidden="true"></span>
				</button>
			<%= err %>
		</div>
	<% end %>
<% end %>
<% if flash.now[:error] %>
	<% flash.now[:error].each do |err| %>
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span class="glyphicon glyphicon-remove"aria-hidden="true"></span>
				</button>
			<%= err %>
		</div>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskListProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag  'shared' %>
  </head>
   
  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: 'layouts/notice' %>
    <main id="main" role="main container">
    <%= yield %>
    </main>
    <%= render partial: "layouts/footer" %>
  </body>
</html>